// Generated by gencpp from file WMR/AddTwoInts.msg
// DO NOT EDIT!


#ifndef WMR_MESSAGE_ADDTWOINTS_H
#define WMR_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <WMR/AddTwoIntsRequest.h>
#include <WMR/AddTwoIntsResponse.h>


namespace WMR
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace WMR


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::WMR::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::WMR::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::WMR::AddTwoInts > {
  static const char* value()
  {
    return "WMR/AddTwoInts";
  }

  static const char* value(const ::WMR::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::WMR::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::WMR::AddTwoInts > 
template<>
struct MD5Sum< ::WMR::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::WMR::AddTwoInts >::value();
  }
  static const char* value(const ::WMR::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::WMR::AddTwoIntsRequest> should match 
// service_traits::DataType< ::WMR::AddTwoInts > 
template<>
struct DataType< ::WMR::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::WMR::AddTwoInts >::value();
  }
  static const char* value(const ::WMR::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::WMR::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::WMR::AddTwoInts > 
template<>
struct MD5Sum< ::WMR::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::WMR::AddTwoInts >::value();
  }
  static const char* value(const ::WMR::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::WMR::AddTwoIntsResponse> should match 
// service_traits::DataType< ::WMR::AddTwoInts > 
template<>
struct DataType< ::WMR::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::WMR::AddTwoInts >::value();
  }
  static const char* value(const ::WMR::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WMR_MESSAGE_ADDTWOINTS_H
